name = "promptvexity"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[env.production]
name = "promptvexity"

[env.preview]
name = "promptvexity-preview"

# Pages configuration
pages_build_output_dir = ".vercel/output/static"